export const imagesCategories = [
    'Election Results',
    'Kobe Bryant',
    'Coronavirus',
    'Tom Hanks',
    'Parasite',
    'WAP',
    'Adele',
    'Naya Rivera',
    'Tiger King',
    'Danny Masterson',
    'Contagion',
    'Shakira',
    'Chadwick Boseman',
    "Anderson Cooper's Baby",
    'Lea Michele',
    'Tom Brady',
    "The Queen's Gambit",
    'Jada Pinkett Smith',
    'Kanye West',
    'Little Women',
    'Doja Cat',
    'Kelly Preston',
    'Ghislaine Maxwell',
    'Van Halen',
]